name: shake_alert_app
description: A Flutter app that detects shakes and triggers an emergency alert.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.0
  audioplayers: ^6.0.0
  vibration: ^2.0.0
  cupertino_icons: ^1.0.6
  noise_meter: ^5.0.0
  permission_handler: ^11.3.0
  avatar_glow: ^3.0.1
  slide_to_act: ^2.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alert_sound.mp3
